name: docker push

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Run script file
        run: |
          chmod +x ./build.sh
          ./build.sh
        shell: bash
      - name: image rename
        run: docker tag vyos:1.5-rolling-202404141045 adenohitu/vyos:1.5-rolling-202404141045
      - name: push DockerHub
        run: docker push adenohitu/vyos:1.5-rolling-202404141045
